export const categories = [
  {
    id: 1,
    name: "Pizza",
    image: require("../assets/images/categories/pizza.png"),
  },
  {
    id: 2,
    name: "Burger",
    image: require("../assets/images/categories/burger.png"),
  },
  {
    id: 3,
    name: "Italian",
    image: require("../assets/images/categories/italian.png"),
  },
  {
    id: 4,
    name: "Chinese",
    image: require("../assets/images/categories/chinese.png"),
  },
  {
    id: 5,
    name: "Noodles",
    image: require("../assets/images/categories/noodles.png"),
  },
  {
    id: 6,
    name: "Sweets",
    image: require("../assets/images/categories/sweets.png"),
  },
];

export const featured = {
  id: 1,
  title: "Hot and Spicy",
  description: "soft and tender fried chicken",

  restaurants: [
    {
      id: 1,
      name: "Papa Johns",
      image: require("../assets/images/restaurant/papajhons.png"),
      description: "Hot and spicy pizzas",
      lat: 38.2145602,
      lng: -85.5324269,
      address: "432 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Margherita Pizza",
          description: "Classic pizza with fresh mozzarella and basil.",
          price: 12,
          image: require("../assets/images/dishes/margarita.png"),
        },
        {
          id: 2,
          name: "BBQ Chicken Pizza",
          description: "BBQ sauce, grilled chicken, and red onions.",
          price: 14,
          image: require("../assets/images/dishes/bbq.png"),
        },
        {
          id: 3,
          name: "Cheeseburger",
          description: "Juicy beef burger with lettuce, tomato, and cheese.",
          price: 10,
          image: require("../assets/images/dishes/chiseeburger.png"),
        },
        {
          id: 4,
          name: "Caesar Salad",
          description: "Romaine lettuce, croutons, and Caesar dressing.",
          price: 8,
          image: require("../assets/images/dishes/sesar.png"),
        },
        {
          id: 5,
          name: "Pasta Primavera",
          description: "Pasta with seasonal vegetables and olive oil.",
          price: 11,
          image: require("../assets/images/dishes/pasta.png"),
        },
        {
          id: 6,
          name: "Shrimp Scampi",
          description: "Sautéed shrimp with garlic and lemon over pasta.",
          price: 16,
          image: require("../assets/images/dishes/shrim.png"),
        },
        {
          id: 7,
          name: "Tacos",
          description: "Soft tacos with beef, lettuce, and salsa.",
          price: 9,
          image: require("../assets/images/dishes/tacos.png"),
        },
        {
          id: 8,
          name: "Sushi Platter",
          description: "An assortment of fresh sushi rolls.",
          price: 18,
          image: require("../assets/images/dishes/sushi.png"),
        },
        {
          id: 9,
          name: "Chocolate Cake",
          description: "Rich chocolate cake with ganache frosting.",
          price: 6,
          image: require("../assets/images/dishes/cake.png"),
        },
      ],
    },
    {
      id: 2,
      name: "Green Salads",
      image: require("../assets/images/restaurant/japan.png"),
      description: "Hot and spicy pizzas",
      lat: 38.2145602,
      lng: -85.5324269,
      address: "432 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Margherita Pizza",
          description: "Classic pizza with fresh mozzarella and basil.",
          price: 12,
          image: require("../assets/images/dishes/margarita.png"),
        },
        {
          id: 2,
          name: "BBQ Chicken Pizza",
          description: "BBQ sauce, grilled chicken, and red onions.",
          price: 14,
          image: require("../assets/images/dishes/bbq.png"),
        },
        {
          id: 3,
          name: "Cheeseburger",
          description: "Juicy beef burger with lettuce, tomato, and cheese.",
          price: 10,
          image: require("../assets/images/dishes/chiseeburger.png"),
        },
        {
          id: 4,
          name: "Caesar Salad",
          description: "Romaine lettuce, croutons, and Caesar dressing.",
          price: 8,
          image: require("../assets/images/dishes/sesar.png"),
        },
        {
          id: 5,
          name: "Pasta Primavera",
          description: "Pasta with seasonal vegetables and olive oil.",
          price: 11,
          image: require("../assets/images/dishes/pasta.png"),
        },
        {
          id: 6,
          name: "Shrimp Scampi",
          description: "Sautéed shrimp with garlic and lemon over pasta.",
          price: 16,
          image: require("../assets/images/dishes/shrim.png"),
        },
        {
          id: 7,
          name: "Tacos",
          description: "Soft tacos with beef, lettuce, and salsa.",
          price: 9,
          image: require("../assets/images/dishes/tacos.png"),
        },
        {
          id: 8,
          name: "Sushi Platter",
          description: "An assortment of fresh sushi rolls.",
          price: 18,
          image: require("../assets/images/dishes/sushi.png"),
        },
        {
          id: 9,
          name: "Chocolate Cake",
          description: "Rich chocolate cake with ganache frosting.",
          price: 6,
          image: require("../assets/images/dishes/cake.png"),
        },
      ],
    },
    {
      id: 3,
      name: "Burger King",
      image: require("../assets/images/restaurant/burgerking.png"),
      description: "Hot and spicy pizzas",
      lat: 38.2145602,
      lng: -85.5324269,
      address: "432 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Margherita Pizza",
          description: "Classic pizza with fresh mozzarella and basil.",
          price: 12,
          image: require("../assets/images/dishes/margarita.png"),
        },
        {
          id: 2,
          name: "BBQ Chicken Pizza",
          description: "BBQ sauce, grilled chicken, and red onions.",
          price: 14,
          image: require("../assets/images/dishes/bbq.png"),
        },
        {
          id: 3,
          name: "Cheeseburger",
          description: "Juicy beef burger with lettuce, tomato, and cheese.",
          price: 10,
          image: require("../assets/images/dishes/chiseeburger.png"),
        },
        {
          id: 4,
          name: "Caesar Salad",
          description: "Romaine lettuce, croutons, and Caesar dressing.",
          price: 8,
          image: require("../assets/images/dishes/sesar.png"),
        },
        {
          id: 5,
          name: "Pasta Primavera",
          description: "Pasta with seasonal vegetables and olive oil.",
          price: 11,
          image: require("../assets/images/dishes/pasta.png"),
        },
        {
          id: 6,
          name: "Shrimp Scampi",
          description: "Sautéed shrimp with garlic and lemon over pasta.",
          price: 16,
          image: require("../assets/images/dishes/shrim.png"),
        },
        {
          id: 7,
          name: "Tacos",
          description: "Soft tacos with beef, lettuce, and salsa.",
          price: 9,
          image: require("../assets/images/dishes/tacos.png"),
        },
        {
          id: 8,
          name: "Sushi Platter",
          description: "An assortment of fresh sushi rolls.",
          price: 18,
          image: require("../assets/images/dishes/sushi.png"),
        },
        {
          id: 9,
          name: "Chocolate Cake",
          description: "Rich chocolate cake with ganache frosting.",
          price: 6,
          image: require("../assets/images/dishes/cake.png"),
        },
      ],
    },
    {
      id: 4,
      name: "Chinese & Sushi Express",
      image: require("../assets/images/restaurant/tavuk.png"),
      description: "Hot and spicy pizzas",
      lat: 38.2145602,
      lng: -85.5324269,
      address: "432 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Margherita Pizza",
          description: "Classic pizza with fresh mozzarella and basil.",
          price: 12,
          image: require("../assets/images/dishes/margarita.png"),
        },
        {
          id: 2,
          name: "BBQ Chicken Pizza",
          description: "BBQ sauce, grilled chicken, and red onions.",
          price: 14,
          image: require("../assets/images/dishes/bbq.png"),
        },
        {
          id: 3,
          name: "Cheeseburger",
          description: "Juicy beef burger with lettuce, tomato, and cheese.",
          price: 10,
          image: require("../assets/images/dishes/chiseeburger.png"),
        },
        {
          id: 4,
          name: "Caesar Salad",
          description: "Romaine lettuce, croutons, and Caesar dressing.",
          price: 8,
          image: require("../assets/images/dishes/sesar.png"),
        },
        {
          id: 5,
          name: "Pasta Primavera",
          description: "Pasta with seasonal vegetables and olive oil.",
          price: 11,
          image: require("../assets/images/dishes/pasta.png"),
        },
        {
          id: 6,
          name: "Shrimp Scampi",
          description: "Sautéed shrimp with garlic and lemon over pasta.",
          price: 16,
          image: require("../assets/images/dishes/shrim.png"),
        },
        {
          id: 7,
          name: "Tacos",
          description: "Soft tacos with beef, lettuce, and salsa.",
          price: 9,
          image: require("../assets/images/dishes/tacos.png"),
        },
        {
          id: 8,
          name: "Sushi Platter",
          description: "An assortment of fresh sushi rolls.",
          price: 18,
          image: require("../assets/images/dishes/sushi.png"),
        },
        {
          id: 9,
          name: "Chocolate Cake",
          description: "Rich chocolate cake with ganache frosting.",
          price: 6,
          image: require("../assets/images/dishes/cake.png"),
        },
      ],
    },
  ],
};
